version: "3"

services:
  zillowapi:
    build:
      context: .
      dockerfile: development/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - development.env
    volumes:
      - ./:/app
    command: ./zillowapi/container_boot.sh
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
     pgdata:
